development:
  adapter: redis
  url: <%= AppConfig.redis.url %>
  channel_prefix: rb_test_fork_development

test:
  adapter: test

staging:
  adapter: redis
  urll: <%= AppConfig.redis.url %>
  channel_prefix: rb_test_fork_staging

production:
  adapter: redis
  url: <%= AppConfig.redis.url %>
  channel_prefix: rb_test_fork_production
