development:
  adapter: redis
  url: <%= AppConfig.redis.url %>
  channel_prefix: rb_test_final_development

test:
  adapter: test

staging:
  adapter: redis
  urll: <%= AppConfig.redis.url %>
  channel_prefix: rb_test_final_staging

production:
  adapter: redis
  url: <%= AppConfig.redis.url %>
  channel_prefix: rb_test_final_production
