development:
  adapter: redis
  url: <%= AppConfig.redis.url %>
  channel_prefix: blueprint_final_test_development

test:
  adapter: test

staging:
  adapter: redis
  urll: <%= AppConfig.redis.url %>
  channel_prefix: blueprint_final_test_staging

production:
  adapter: redis
  url: <%= AppConfig.redis.url %>
  channel_prefix: blueprint_final_test_production
