default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  user: 
  password: 

development:
  <<: *default
  database: rb_deployment_test_development

staging:
  <<: *default
  database: rb_deployment_test_staging

production:
  <<: *default
  database: rb_deployment_test_production

test:
  <<: *default
  database: rb_deployment_test_test
